### ISSUE TITLE
Crash when running officetxt

### ISSUE THREAD

**Issue by bararchy** [officetxt/officetxt#1]
```bash
activerecord-5.1.2/lib/active_record/migration.rb:525:in `inherited': Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: (StandardError)
```

**Comment by geraldb** [comment]
Thanks for reporting. Do you mind to publish / post the complete log / console dump? Cheers.

**Comment by bararchy** [comment]
@geraldb Full crash:

```ruby
slideshow-models/3.3.0 on Ruby 2.4.1 (2017-03-22) [x86_64-linux]
slideshow-templates/3.0.0 on Ruby 2.4.1 (2017-03-22) [x86_64-linux]
journaltxt/1.0.1 on Ruby 2.4.1 (2017-03-22) [x86_64-linux]
feedparser/2.0.1 (with rss/0.2.7 n json/2.1.0) on Ruby 2.4.1 (2017-03-22) [x86_64-linux]
feedfilter/1.1.1 on Ruby 2.4.1 (2017-03-22) [x86_64-linux]
activerecord-utils/0.4.0 (activerecord/5.1.2) on Ruby 2.4.1 (2017-03-22) [x86_64-linux]
/home/unshadow/.gem/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:525:in `inherited': Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: (StandardError)

  class ActivityDb::CreateDb < ActiveRecord::Migration[4.2]
	from /home/unshadow/.gem/ruby/2.4.0/gems/activityutils-0.1.0/lib/activityutils/schema.rb:3:in `<module:ActivityDb>'
	from /home/unshadow/.gem/ruby/2.4.0/gems/activityutils-0.1.0/lib/activityutils/schema.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/unshadow/.gem/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/unshadow/.gem/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/unshadow/.gem/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
	from /home/unshadow/.gem/ruby/2.4.0/gems/activityutils-0.1.0/lib/activityutils.rb:5:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/unshadow/.gem/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
	from /home/unshadow/.gem/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/unshadow/.gem/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
	from /home/unshadow/.gem/ruby/2.4.0/gems/pluto-models-1.4.0/lib/pluto/models.rb:29:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/unshadow/.gem/ruby/2.4.0/gems/pluto-1.2.3/lib/pluto.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/unshadow/.gem/ruby/2.4.0/gems/officetxt-0.1.1/lib/officetxt.rb:14:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/unshadow/.gem/ruby/2.4.0/gems/officetxt-0.1.1/bin/officetxt:3:in `<top (required)>'
	from /home/unshadow/.gem/ruby/2.4.0/bin/officetxt:22:in `load'
	from /home/unshadow/.gem/ruby/2.4.0/bin/officetxt:22:in `<main>'

```

**Comment by geraldb** [comment]
@bararchy  Thanks for the log. Looks like it's 

> activerecord-utils/0.4.0 (activerecord/5.1.2) on Ruby 2.4.1 (2017-03-22) [x86_64-linux]

causing the trouble. Will try to fix it over the next weeks. As a workaround for now you can "downgrade" ActiveRecord to the 4.2.x series, that is, use a Gemfile and add the officetxt gem plus activerecord nailed to 4.2.x.    Thanks again. Cheers.

**Comment by powder** [comment]
After doing a Gemfile to pin the version of activerecord, I got the following

```
slideshow-models/3.3.0 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
slideshow-templates/3.0.0 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
journaltxt/1.0.1 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
feedparser/2.0.1 (with rss/0.2.7 n json/2.0.2) on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
feedfilter/1.1.1 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
activerecord-utils/0.4.0 (activerecord/4.2.9) on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
activityutils/0.1.0 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
confdb/0.1.0 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
logdb/0.2.1 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
pluto-models/1.4.0 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
pluto-feedfetcher/0.1.0 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
preproc/0.1.0 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
pluto-update/1.6.0 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
pluto-merge/1.1.0 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
pluto-tasks/1.5.3 on Ruby 2.4.1 (2017-03-22) [x86_64-darwin16]
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- jekyll-feed (LoadError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/officetxt-0.1.1/lib/officetxt.rb:31:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/officetxt-0.1.1/bin/officetxt:3:in `<top (required)>'
	from /usr/local/bin/officetxt:22:in `load'
	from /usr/local/bin/officetxt:22:in `<main>'
```

I simply added jekyll-feed to the Gemfile as well to resolve, but, it seems this dependency is being missed inside of officetxt.

**Comment by geraldb** [comment]
@powder Thanks for trying and reporting. Will add the missing jekyll-feed gem /dependency. That's an easy fix. Thanks again.
